# Generated by Django 3.2.25 on 2025-04-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pregnancy_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
